### ISSUE TITLE
Severe delay in note mode with Drum Machine

### ISSUE THREAD

**Issue by lokanchung** [Jengamon/Launchpad-X-Bitwig-Script#18]
With drum machine layout in note mode, holding one pad down and pressing another pad causes huge delay, inputs are sometimes ignored.

**Comment by Jengamon** [comment]
Noticed this bug, and ee2d2f9547a710d26349d32a045709a86b2d1e1a should fix it.

**Comment by Jengamon** [comment]
Just pick up https://github.com/Jengamon/Launchpad-X-Bitwig-Script/releases/tag/v1.2 and it should all work

**Comment by Jengamon** [comment]
Reopen if it doesn't fix the problem for you.

**Comment by lokanchung** [comment]
I've been busy so it took quite long to test it.
It's not fixed and. The delay is still present.  Try keep hitting one pad while holding another one.

Custom mode works fine so I'm not gonna bug you with this any more.
Reopening the issue is up to you as you closed it. (I don't have rights)

**Comment by Jengamon** [comment]
Oh, if it's in note mode (where you have magenta and blue pads), this script doesn't exert any control over that.
Because we use DAW mode, the device itself is responsible for controlling that mode (coloring/sending notes/etc.)
The only mode that this script controls out of the note input modes is the drum pad mode, which shows up only when 
a Drum Machine is active. 

A video would be really cool to see whats going on, if possible.

**Comment by Jengamon** [comment]
When you open a new project and connect the controller, then go to Studio I/O and open up the Studio I/O tab, could you screenshot what you see?

I'm doing what you say (holding one pad down, and pressing another very quickly), but I'm not getting the same problem.

**Comment by Jengamon** [comment]
[![giftrick](https://i.imgur.com/QOekxTr.gif)](https://streamable.com/35gxaj)
This is me attempting to reproduce the bug. (click for the higher quality video version w/ sound to prove responsiveness)

**Comment by lokanchung** [comment]
Here's the screenshot of  Studio I/O panel.
![image](https://user-images.githubusercontent.com/5680289/102452977-aef0b680-407e-11eb-8b62-4c16a4fa9dc4.png)

and video: playability difference + delay demo
https://imgur.com/Xq3Rzaa

**Comment by Jengamon** [comment]
Try using this version of LaunchpadX, and see if anything changes:

https://www.dropbox.com/s/mt175faaycmguqr/LaunchpadX.bwextension?dl=0

**Comment by lokanchung** [comment]
Nothings changed. Do you have the actual device or are you using something from SDK? If you don't have one, maybe I can contribute when I get some free time.

**Comment by Jengamon** [comment]
I am actually using an actual device. 

Have you upgraded the firmware of the Launchpad X?
Is the device connected directly to your computer, or through a hub?

Try reinitializing the controller script, does that help?

**Comment by lokanchung** [comment]
Yes I'm running 1.0.4. Is there any specific way for initializing it? I tried removing and adding back from controller settings in Bitwig.

**Comment by Jengamon** [comment]
No there isn't a specific different way to initialize.
Are there a lot of other controllers connected?

**Comment by Jengamon** [comment]
Try triggering the bug while interacting with Bitwig (creating new instruments, triggering other pads on screen, etc.). Is Bitwig unresponsive?

**Comment by lokanchung** [comment]
No, I have NI Komplete Kontrol S61 MK2 and didn't make different with it or not, and Bitwig doesn't slow down at all.

I just tested it on Macbook and Surface, got an odd result.
In Mac, drum mode worked fine but there was no light (session and drum modes, which are managed by the script)
I had the issue on Surface as in my main Windows desktop.

So, it could be either lights (redrawing) or some OS specific problem?

**Comment by Jengamon** [comment]
Ok, I tried on a Linux, and the script does slow down and miss inputs if the system overall is busy, mostly because it relies on Bitwig to tell it if a pad is hit or not, so I can only try and make the only repetitive task a bit more spaced out.

When on a Mac, did *no* lights show up anywhere on the device? That seems odd, tho I haven't really tested on Mac (as I own none), so I can't really say anything about it. I'm not really doing anything OS-specific ;;;-_-

try this for size: https://www.dropbox.com/s/mt175faaycmguqr/LaunchpadX.bwextension?dl=0

edited https://github.com/Jengamon/Launchpad-X-Bitwig-Script/blob/master/src/main/java/io/github/jengamon/novation/modes/DrumPadMode.java#L137 from 300L (so around 3 times a second) to 1000L (around 1 sec).

**Comment by lokanchung** [comment]
That didn't fix either, And, you are running Windows and don't have the issue. This is getting nasty, I'll do more testing and keep you updated when my current project is done.

**Comment by Jengamon** [comment]
Thanks! I'll be waiting~

**Comment by lokanchung** [comment]
NoteButtons listeneing to channel pressure caused the issue. 

When Launchpad X's aftertouch is set to channel pressure, instead of polyphonic aftertouch, button release event is not fired by the host until channel pressure reaches zero.

This could be fixed by adding a separate control listening to channel pressure message. 

#20

**Comment by Jengamon** [comment]
Just for future reference, new commits and features should be based off of the api-10 branch rather than master
